version: '3.8'

services:
  gaof_weather:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - gaof_network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - UVICORN_WORKERS=2
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]

networks:
  gaof_network:
